通知表示関数
kajiLabTeam/TrainAlert2 pull request #10
Opened 2024-10-11 09:54 UTC by moridokin

通知を表示する関数を書きました。

2024-10-13 01:03 UTC, harutiro requested changes
レビューしました！

PRの粒度感いい感じです！
すこし変更して欲しいところがありますので対応おねがいします🙇

2024-10-13 01:03 UTC, harutiro commented on app/src/main/java/net/harutiro/trainalert2/features/notification/api/NotificationApi.kt
> +    }
ここの書き方いいですね！
initで最初から呼び出すことを前提にしているのはいいと思います。

2024-10-13 01:03 UTC, harutiro commented on app/src/main/java/net/harutiro/trainalert2/features/notification/api/NotificationApi.kt
> +        val message = "目的地に到着しました"
showNotificationという関数では、もっと可変的に通知を発行できた方が今後融通がきくと思います。
関数の引数でtitleとmessageを追加して、自由に変更してみるのはどうでしょうか？

2024-10-13 01:03 UTC, harutiro commented on app/src/main/java/net/harutiro/trainalert2/features/notification/api/NotificationApi.kt
> +            .setSmallIcon(android.R.drawable.ic_dialog_info)
ここは、今後アイコンが追加されたら、アプリアイコンにするといいですね。

2024-10-13 01:03 UTC, harutiro commented on app/src/main/java/net/harutiro/trainalert2/features/notification/api/NotificationApi.kt
通知を表示する関数ができたら、できればそれを確認できるコードを書いてチェックしやすくしておくとよりいいです。
確認できるコードがなかったとしても、デモで動いているシーンをスクショしてもらってもいいかもです。

2024-10-14 14:11 UTC, moridokin commented on app/src/main/java/net/harutiro/trainalert2/features/notification/api/NotificationApi.kt
分かりました。次回から実践したいのですが、動作確認できるコードをどこに書けばいいかわからないです。個人で確認用のプロジェクトを作り、その中で動作確認したスクショを添付すれば大丈夫ですか。

2024-10-14 14:42 UTC, harutiro reviewed
レビューしました。

2024-10-14 14:42 UTC, harutiro commented on app/src/main/java/net/harutiro/trainalert2/features/notification/api/NotificationApi.kt
できれば個人確認ようのプロジェクトではなく、このプロジェクトで、動かせるように変更して欲しいです。
homeScreenは現状何もやっていないので、そこで少し動作検証をするボタンをなどを作成して、レビューが終われば消してマージをするといったやり方ができます！

2024-10-16 01:44 UTC, closed without merging