入力フォームの保存機能
kajiLabTeam/TrainAlert2 pull request #14
Opened 2024-10-15 08:40 UTC by nekonekocatcat

データを入力フォームに入力し保存ボタンを押すとデータベース上にデータを保存する。
また、HomeScreen上でデータベース上のデータをリスト化して表示しました。スクロール機能もつけました。
現状の問題点として、UIが見ずらい点や保存ボタンが押された後一度アプリを更新しないと反映されないという点がありますが、今回は見逃してください。次に実装します。

2024-10-16 05:42 UTC, harutiro requested changes
レビューしました。
大体問題ないです。

2024-10-16 05:42 UTC, harutiro commented on app/src/main/java/net/harutiro/trainalert2/Application.kt
クラス名を変更した理由は何かありましたか？
何かと干渉してしまった感じでしょうか？

その場合、Myだと結構普遍的な名前になってしまうので、TrainAlertであることがわかる名前にした方がいいかもしれないです。

2024-10-16 06:21 UTC, nekonekocatcat commented on app/src/main/java/net/harutiro/trainalert2/Application.kt
MyApplicationからTrainAlertApplicationに変更しました

2024-10-16 06:34 UTC, harutiro reviewed
レビューをしました。

2024-10-16 06:34 UTC, harutiro commented on app/src/main/java/net/harutiro/trainalert2/core/presenter/home/HomeViewModel.kt
> +        }
現状は、daoからデータを取り出す時は、単純に一行書くだけで大丈夫ではありますが、今後、データの取得に条件分岐が入ったときに、コードが長くなってしまう可能性があるので、Repositoryにデータを取得する処理を書いた方が良さそうです。

ViewModelScopeはここで大丈夫です。

2024-10-16 06:34 UTC, harutiro commented on app/src/main/java/net/harutiro/trainalert2/core/presenter/routeEditer/RouteEditorViewModel.kt
> +        }
ここのデータを保存する処理に関しても、バリデーションチェックを行う処理をRepositoryに新しくかいたほうがいいかもしれないです。
その方が、他のクラスなどから取得をする処理を書いたときに、汎用性が高くなるかと思います。
一度マージだけはしてしまって、別のPRでやっても大丈夫です。

2024-10-16 06:35 UTC, harutiro reviewed
レビューしました。

2024-10-16 06:35 UTC, harutiro commented on app/src/main/java/net/harutiro/trainalert2/core/presenter/routeEditer/RouteEditorScreen.kt
> +            toBackScreen() // 戻る処理
ちゃんと戻る処理が書いてあるのはいいね。
よく忘れがち

2024-10-22 07:57 UTC, harutiro approved these changes
LGTM OKです

2024-10-22 07:58 UTC, merged